### ISSUE TITLE
How to control an intensity of a sun light?

### ISSUE THREAD

**Issue by ProgrammingLife** [Dragosha/defold-light-and-shadows#1]
Is there a way to make scene extra bright but increasing the sun value? Can't find that controller.
I tried to set Color Max to 0.2 and I got dark scene as expected but when I set the value to 100.0 then nothing changes even if I set the value to 1.0.

As well for bulbs. How do I increase an intensity for bulb point lights?

**Comment by Dragosha** [comment]
Try to set color value in the sun object. https://github.com/Dragosha/defold-light-and-shadows#sun

"Color Max" just limit the final light factor of pixel.

> intensity for bulb

color and power.
